/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppLayout: typeof import('./src/components/AppLayout.vue')['default']
    CategoryChart: typeof import('./src/components/CategoryChart.vue')['default']
    CategoryOverTimeChart: typeof import('./src/components/CategoryOverTimeChart.vue')['default']
    ContentAgeChart: typeof import('./src/components/ContentAgeChart.vue')['default']
    DayOfWeekChart: typeof import('./src/components/DayOfWeekChart.vue')['default']
    DurationDistributionChart: typeof import('./src/components/DurationDistributionChart.vue')['default']
    GenreChart: typeof import('./src/components/GenreChart.vue')['default']
    GenreOverTimeChart: typeof import('./src/components/GenreOverTimeChart.vue')['default']
    HourChart: typeof import('./src/components/HourChart.vue')['default']
    LanguageChart: typeof import('./src/components/LanguageChart.vue')['default']
    MonthlyChart: typeof import('./src/components/MonthlyChart.vue')['default']
    MoreDataInfo: typeof import('./src/components/MoreDataInfo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UAlert: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Alert.vue')['default']
    UApp: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UBadge: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Badge.vue')['default']
    UButton: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UCard: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Card.vue')['default']
    UCheckbox: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Checkbox.vue')['default']
    UIcon: typeof import('./node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
    UInput: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
    WatchTimeChart: typeof import('./src/components/WatchTimeChart.vue')['default']
    YouTubeApiPanel: typeof import('./src/components/YouTubeApiPanel.vue')['default']
  }
}
